version: "2.1"
orbs:
  codecov: codecov/codecov@3.2.3
    ignore:
      - "**/api"
      - "init-firebase.js"
  node: circleci/node@5.0.2

jobs:
  test:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run:
          name: install npm
          command: sudo npm install -g npm@latest
      - run:
          name: install cart
          command: npm i react-use-cart
      - run:
          name: install firebase
          command: npm install firebase --save
      - run:
          name: install material ui
          command: npm install @mui/material @emotion/react @emotion/styled --save
      - run:
          name: install material ui icons
          command: npm install @mui/icons-material @mui/material @emotion/styled @emotion/react --save
      - run:
          name: install material ui styled
          command: npm install --save styled-components --save
      - run:
          name: run tests
          command: npm run test -- --coverage

      - codecov/upload
workflows:
  test_my_app:
    jobs:
      - test