version: '2.1'
orbs: 
  node: circleci/node@4.7.0
jobs:
  test:
    docker:
      - image: cimg/node:current
    #executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: 
          name: install npm
          command: sudo npm install -g npm@latest
      - run: 
          name: run tests
          command: npm run test
workflows:
  test_my_app:
    jobs:
      - test
